config/routes.rb
Metube::Application.routes.draw do
  get "/videos/gladiator" => "videos#show_gladiator", as: 'gladiator_video'
  get "/videos/air_force_one" => "videos#show_air_force_one", as: 'air_force_one_video'
  get "/videos/nelly" => "videos#show_nelly", as: 'nelly_video'
  get "/videos/dream_theater" => "videos#show_dream_theater", as: 'dream_theater_video'

  get "/posts/jersey_city" => "posts#show_jersey_city", as: 'jersey_city'
  get "/posts/el_paso" => "posts#show_el_paso", as: 'el_paso'

  root "main#show_list"
  get "/videos" => "main#show_list", as: 'show_list'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def show_list
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show_jersey_city
    
  end

  def show_el_paso
    
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def show_gladiator
    @video = {
      :title => "Gladiatator",
      :description => "This is a movie where Russell Crowe is fightin' round the world",
      :youtube_id => "FI1ylg4GKv8"
    }
  end

  def show_air_force_one
  end

  def show_nelly
  end

  def show_dream_theater
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metube</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/show_list.html.erb
<ul> Great video clips from movies and TV
  <li><%= link_to "Death Top America", gladiator_video_path %></li>
  <li><%= link_to "Death To America and Buttersauce", air_force_one_video_path %></li>
  <li><%= link_to "This guy....", nelly_video_path %></li>
  <li><%= link_to "Alejandro", dream_theater_video_path %></li>
</ul>

app/views/posts/show_el_paso.html.erb
Tacos?
Chuco Town

app/views/posts/show_jersey_city.html.erb
Is Ho-boken a real place.

app/views/videos/show_air_force_one.html.erb
<h1>Air Force One</h1>

<iframe width="420" height="315" src="//www.youtube.com/embed/sOUoNy7EmPA" frameborder="0" allowfullscreen></iframe>

<p>Wait, this isn't the Nelly video I was looking for!</p>

<%= link_to "Back", show_list_path %>

app/views/videos/show_dream_theater.html.erb
<h1>Dream Theater - Pull Me Under</h1>

<iframe width="560" height="315" src="//www.youtube.com/embed/Eqiotc_fKQ4" frameborder="0" allowfullscreen></iframe>

<p>Little children whaling. Y'arrrrr</p>

<%= link_to "Back", show_list_path %>

app/views/videos/show_gladiator.html.erb
<h1><%= @video[:title] %></h1>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%= @video[:youtube_id]%>" frameborder="0" allowfullscreen></iframe>

<p><%= @video[:description] %></p>

<%= link_to "Back", show_list_path %>

app/views/videos/show_nelly.html.erb
<h1>Ur Force Wunzzzz</h1>

<iframe width="420" height="315" src="//www.youtube.com/embed/y-ZnUlkuC8s" frameborder="0" allowfullscreen></iframe>

<p>Nelly shows everyone what's up.</p>

<%= link_to "Back", show_list_path %>